/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"

str_t *hello_world_1_svc(void *argp, struct svc_req *rqstp) {
  static str_t result;
  const char str[] = "Hello, world!";

  result.buf.buf_len = strlen(str);
  result.buf.buf_val = strdup(str);

  printf("server: %s\n", result.buf.buf_val);

  return &result;
}
