/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct str_s str_t;

struct str_s {
	struct {
		u_int buf_len;
		char *buf_val;
	} buf;
};
typedef struct str_s str_s;

#define HELLOPROG 200001
#define HELLOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HELLO_WORLD 0
extern  str_t * hello_world_1(void *, CLIENT *);
extern  str_t * hello_world_1_svc(void *, struct svc_req *);
extern int helloprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HELLO_WORLD 0
extern  str_t * hello_world_1();
extern  str_t * hello_world_1_svc();
extern int helloprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_str_s (XDR *, str_s*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_str_s ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
